AuctionApp/config/routes.rb
Rails.application.routes.draw do
  resources :auctions
  get 'home/index'

end

AuctionApp/app/models/auction.rb
class Auction < ActiveRecord::Base
end

AuctionApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

AuctionApp/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.require(:auction).permit(:auction_item, :auction_id, :item_owner)
    end
end

AuctionApp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

AuctionApp/app/helpers/application_helper.rb
module ApplicationHelper
end

AuctionApp/app/helpers/auctions_helper.rb
module AuctionsHelper
end

AuctionApp/app/helpers/home_helper.rb
module HomeHelper
end

AuctionApp/app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auction_item %><br>
    <%= f.text_field :auction_item %>
  </div>
  <div class="field">
    <%= f.label :auction_id_ %><br>
    <%= f.number_field :auction_id %>
  </div>
  <div class="field">
    <%= f.label :item_owner %><br>
    <%= f.text_field :item_owner %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AuctionApp/app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

AuctionApp/app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Auctions</h1>

<table>
  <thead>
    <tr>
      <th>Auction item</th>
      <th>Auction Id</th>
      <th>Item owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.auction_item %></td>
        <td><%= auction.auction_id %></td>
        <td><%= auction.item_owner %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

AuctionApp/app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

AuctionApp/app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auction item:</strong>
  <%= @auction.auction_item %>
</p>

<p>
  <strong>Auction Id:</strong>
  <%= @auction.auction_id %>
</p>

<p>
  <strong>Item owner:</strong>
  <%= @auction.item_owner %>
</p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>

AuctionApp/app/views/home/index.html.erb
<h1>WELCOME TO AUCTION</h1>
<%= link_to 'Auctions List', auctions_path %>

AuctionApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>